<?xml version="1.0" encoding="utf-8"?><Database Name="lever_Deduplication" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=lever_Deduplication;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="lever_DeduplicationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_login" Member="tb_logins">
    <Type Name="tb_login">
      <Column Name="lid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="st" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="utype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_user_registration" Member="tb_user_registrations">
    <Type Name="tb_user_registration">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="skey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_auditor" Member="tb_auditors">
    <Type Name="tb_auditor">
      <Column Name="aid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="aname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phne" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="rdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_filename_checking" Member="tb_filename_checkings">
    <Type Name="tb_filename_checking">
      <Column Name="fnid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="uploader" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="count" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="attepmt_date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_sector" Member="tb_sectors">
    <Type Name="tb_sector">
      <Column Name="sid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="shash" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ekey" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_filename_checking" Member="tb_filename_checking1s">
    <Type Name="tb_filename_checking1">
      <Column Name="fnid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="uploader" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="count" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="attepmt_date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_temp" Member="tb_temps">
    <Type Name="tb_temp">
      <Column Name="ffid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.download" Member="downloads">
    <Type Name="download">
      <Column Name="did" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="download" Member="download1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="failed" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_upload" Member="tb_uploads">
    <Type Name="tb_upload">
      <Column Name="fid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="upload_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="upload_date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="duplicated_st" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hash" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="duplicated_parts" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="non_duplicated_parts" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="splited_hashes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ext" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_blocked_status" Member="tb_blocked_status">
    <Type Name="tb_blocked_status">
      <Column Name="bid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bst" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>